version: "3.9" 
services:
    postgres:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 5432:5432
        volumes:
          - ./src:/app/src
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
